// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TAttractionTag
{
    public int FTagId { get; set; }

    public string FTagName { get; set; }

    public DateTime? FCreatedDate { get; set; }

    public virtual ICollection<TAttractionJoinAttractionTag> TAttractionJoinAttractionTags { get; set; } = new List<TAttractionJoinAttractionTag>();
}