// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TAttractionRecommendation
{
    public int FAttractionRecommendationId { get; set; }

    public int? FAttractionId { get; set; }

    public int? FRecommendationId { get; set; }

    public string FReason { get; set; }

    public DateTime? FCreatedDate { get; set; }

    public virtual TAttraction FAttraction { get; set; }

    public virtual TAttraction FRecommendation { get; set; }
}