// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TAttractionView
{
    public int FId { get; set; }

    public int? FAttractionId { get; set; }

    public int? FViewCount { get; set; }

    public virtual TAttraction FAttraction { get; set; }
}