// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TChatRoom
{
    public int FChatId { get; set; }

    public int? FUserId { get; set; }

    public DateTime? FChatStartTime { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TMessage> TMessages { get; set; } = new List<TMessage>();
}