// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TChat
{
    public int FChatId { get; set; }

    public int? FSenderId { get; set; }

    public int? FReceiverId { get; set; }

    public string FMessageText { get; set; }

    public DateTime? FSentAt { get; set; }

    public virtual TUser FReceiver { get; set; }

    public virtual TUser FSender { get; set; }
}