// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TEventContact
{
    public int FContactId { get; set; }

    public int? FEventId { get; set; }

    public string FContactName { get; set; }

    public string FContactPhone { get; set; }

    public string FContactEmail { get; set; }

    public virtual TEvent FEvent { get; set; }
}