// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TEventLog
{
    public int FLogId { get; set; }

    public int? FEventId { get; set; }

    public string FAction { get; set; }

    public DateTime? FActionDate { get; set; }

    public int? FUserId { get; set; }

    public string FDetails { get; set; }

    public virtual TEvent FEvent { get; set; }

    public virtual TUser FUser { get; set; }
}