// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TEventSchedule
{
    public int FScheduleId { get; set; }

    public int? FEventId { get; set; }

    public DateTime? FStartTime { get; set; }

    public DateTime? FEndTime { get; set; }

    public string FScheduleNotes { get; set; }

    public virtual TEvent FEvent { get; set; }
}