// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TEventPayment
{
    public int FPaymentId { get; set; }

    public int? FRegistrationFormId { get; set; }

    public DateTime? FPaymentDate { get; set; }

    public decimal? FAmount { get; set; }

    public string FPaymentStatus { get; set; }

    public string FPaymentMethod { get; set; }

    public virtual TEventRegistrationForm FRegistrationForm { get; set; }
}