// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TEventLocation
{
    public int FLocationId { get; set; }

    public int? FEventId { get; set; }

    public string FLocationName { get; set; }

    public string FAddress { get; set; }

    public virtual TEvent FEvent { get; set; }
}