// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TEventCategory
{
    public int FEventCategoryId { get; set; }

    public string FEventCategoryName { get; set; }

    public int? FParentCategoryId { get; set; }

    public string FEventDescriptionn { get; set; }

    public DateTime? FEventCreatedDate { get; set; }

    public virtual TEventCategory FParentCategory { get; set; }

    public virtual ICollection<TEventCategory> InverseFParentCategory { get; set; } = new List<TEventCategory>();

    public virtual ICollection<TEventCategoryMapping> TEventCategoryMappings { get; set; } = new List<TEventCategoryMapping>();
}