// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TEventFavorite
{
    public int FFavoriteId { get; set; }

    public int? FEventId { get; set; }

    public int? FUserId { get; set; }

    public DateTime? FCreatedDate { get; set; }

    public virtual TEvent FEvent { get; set; }

    public virtual TUser FUser { get; set; }
}