// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TEvent
{
    public int FEventId { get; set; }

    public int? FUserId { get; set; }

    public string FEventName { get; set; }

    public string FEventDescription { get; set; }

    public DateTime? FEventStartDate { get; set; }

    public DateTime? FEventEndDate { get; set; }

    public DateTime? FEventCreatedDate { get; set; }

    public DateTime? FEventUpdatedDate { get; set; }

    public string FEventUrl { get; set; }

    public bool? FEventIsActive { get; set; }

    public int? FMaxParticipants { get; set; }  // 最大參與人數

    public int? FCurrentParticipants { get; set; } // 目前參與人數

    public int? FEventDuration { get; set; } // 活動時長（分鐘或小時）

    public decimal? FEventFee { get; set; } // 活動費用

    public virtual ICollection<TEventCategoryMapping> TEventCategoryMappings { get; set; } = new List<TEventCategoryMapping>();

    public virtual ICollection<TEventContact> TEventContacts { get; set; } = new List<TEventContact>();

    public virtual ICollection<TEventFavorite> TEventFavorites { get; set; } = new List<TEventFavorite>();

    public virtual ICollection<TEventImage> TEventImages { get; set; } = new List<TEventImage>();

    public virtual ICollection<TEventLocation> TEventLocations { get; set; } = new List<TEventLocation>();

    public virtual ICollection<TEventLog> TEventLogs { get; set; } = new List<TEventLog>();

    public virtual ICollection<TEventRegistrationForm> TEventRegistrationForms { get; set; } = new List<TEventRegistrationForm>();

    public virtual ICollection<TEventSchedule> TEventSchedules { get; set; } = new List<TEventSchedule>();
}