// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TFriend
{
    public int FRelationshipId { get; set; }

    public int? FUserId { get; set; }

    public int? FFriendId { get; set; }

    public virtual TUser FFriend { get; set; }

    public virtual TUser FUser { get; set; }
}