// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TMessage
{
    public int FMessageId { get; set; }

    public int? FChatId { get; set; }

    public int? FUserId { get; set; }

    public string FMessageText { get; set; }

    public DateTime? Ftimestamp { get; set; }

    public virtual TChatRoom FChat { get; set; }

    public virtual TUser FUser { get; set; }
}