// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TOrderStatus
{
    public int FOrderStatusId { get; set; }

    public string FStatusName { get; set; }

    public virtual ICollection<TOrderStatusHistory> TOrderStatusHistories { get; set; } = new List<TOrderStatusHistory>();

    public virtual ICollection<TOrder> TOrders { get; set; } = new List<TOrder>();
}