// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TOrdersDetail
{
    public int FOrderDetailsId { get; set; }

    public int? FOrderId { get; set; }

    public int? FItemId { get; set; }

    public string FItemType { get; set; }

    public int? FOrderQty { get; set; }

    public decimal? FUnitPrice { get; set; }

    public string FExtraInfo { get; set; }

    public virtual TProduct FItem { get; set; }

    public virtual TOrder FOrder { get; set; }

    public virtual ICollection<TProductReview> TProductReviews { get; set; } = new List<TProductReview>();
}