// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TPostView
{
    public int FViewId { get; set; }

    public int? FUserId { get; set; }

    public int? FPostId { get; set; }

    public virtual TPost FPost { get; set; }

    public virtual TUser FUser { get; set; }
}