// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TProductReview
{
    public int FReviewId { get; set; }

    public int? FOrderDetailsId { get; set; }

    public int? FUserId { get; set; }

    public int? FReviewRating { get; set; }

    public string FReviewComment { get; set; }

    public DateTime? FReviewDate { get; set; }

    public virtual TOrdersDetail FOrderDetails { get; set; }

    public virtual TUser FUser { get; set; }
}