// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TRank
{
    public int FUserRankId { get; set; }

    public string FRankName { get; set; }

    public virtual ICollection<TUser> TUsers { get; set; } = new List<TUser>();
}