// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TShoppingCart
{
    public int FCartId { get; set; }

    public int? FUserId { get; set; }

    public DateTime? FCreatedDate { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TShoppingCartItem> TShoppingCartItems { get; set; } = new List<TShoppingCartItem>();
}