// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TShoppingCartItem
{
    public int FCartItemId { get; set; }

    public int? FCartId { get; set; }

    public string FItemType { get; set; }

    public int? FItemId { get; set; }

    public int? FQuantity { get; set; }

    public decimal? FPrice { get; set; }

    public virtual TShoppingCart FCart { get; set; }
}