// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjGroupB.Models;

public partial class TWallet
{
    public int FTradeId { get; set; }

    public int FUserId { get; set; }

    public int? FAmountChange { get; set; }

    public string FChangeLog { get; set; }

    public DateTime? FChangeTime { get; set; }

    public virtual TUser FUser { get; set; }
}